### ISSUE TITLE
Het startdocument is een stukje documentatie

### ISSUE THREAD

**Issue by Theo-denBlanken** [mikevandiepen/acquired-taste#1]
Graag in pdf hier op GitHub.
Het is niet duidelijk wat er gemaakt gaat worden.
Welke pagina's mogen wij verwachten.
Het eenvoudigst gaat dat door op te geven welke webshopbox  als uitgangspunt bij jouw uitwerking gaat dienen.
[Keuze 1. Webshopbox MV.pdf](https://github.com/mikevandiepen/acquired-taste/files/3261185/Keuze.1.Webshopbox.MV.pdf)

**Comment by mikevandiepen** [comment]
https://bitbucket.org/mikevandiepen/the-acquired-taste/src/master/

Nieuwe repository op bitbucket, ik had wat issues met github lokaal.

**Comment by Theo-denBlanken** [comment]
Dag Mike,

Graag in de readme.md van deze repository een link naar https://github.com/mikevandiepen/acquired-taste leggen .
Je stelt de beoordelaars zo in de gelegenheid het proces wat beter te volgen.


Met vriendelijke groeten,

--

[ma-logo]
Theo den Blanken

[Theo]<http://blanken5.home.xs4all.nl/>
docent
Mediadeveloper
Mediacollege Amsterdam
[Twitter]<https://twitter.com/theodenblanken/> [WordPress] <http://bla.hosts.ma-cloud.nl/>


Van: Mike van Diepen <notifications@github.com>
Beantwoorden - Aan: mikevandiepen/acquired-taste <reply@reply.github.com>
Datum: woensdag 26 juni 2019 om 22:39
Aan: mikevandiepen/acquired-taste <acquired-taste@noreply.github.com>
CC: Theo <T.denBlanken@ma-web.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [mikevandiepen/acquired-taste] Het startdocument is een stukje documentatie (#1)


https://bitbucket.org/mikevandiepen/the-acquired-taste/src/master/

Nieuwe repository op bitbucket, ik had wat issues met github lokaal.
